# Generated by Django 3.0.3 on 2020-02-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.TextField(choices=[('powertool', 'powertool'), ('lawntool', 'lawntool'), ('gardentool', 'gardentool')], max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('borrowed', models.BooleanField()),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
